# -*- coding: utf-8 -*-
"""Copy of Sample EDA Submission Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRWC88B37zppgp_DhmDTLyCQmrlJ5LKN

# **Project Name**    -

##### **Project Type**    - EDA
##### **Contribution**    - Individual
Name- Anjali Prasad

# **Project Summary -**

The aim of this project was to perform exploratory data analysis (EDA) on a hotel booking dataset in order to gain insights into customer behavior and booking patterns. The dataset contained information on hotel bookings, including booking dates, customer demographics, and reservation details First we cleaned and preprocessed the data, which involved removing missing values, handling duplicates. Then we visualized the data using various graphical techniques such as histograms, scatter plots, and heat maps. Through our analysis, we discovered several interesting insights For example we found that most bookings were made between july and August

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Have you ever considered the ideal season of the year to reserve a fhotel room? Alternatively how long should I remain to get the greatest dally rate? What if you wanted to foretell whether a notel would unreasonably frequently receive unusual requests? You can investigate those Questions using the data from hotel reservations: This data collection comprises reservation details for a city hotel and a resort hotel as well as details like the date the reservat or was made the duration of the stav the number of aduits kids, and/or babies and the number of parsing spaces that are available The data is free of any information that may be used to centify an ngividual Explore and assess the uttormat on to

#### **Define Your Business Objective?**

Answer -
Analyse the data on bookings of City Hotel and Resort Hotel to gain insights on the different factors that affect the booking This is undertaken as an individual project

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
from datetime import datetime
import ast

"""### Dataset Loading"""

# Load Dataset

from google.colab import drive
drive.mount('/content/drive')
database="/content/drive/MyDrive/Colab Notebooks/Hotel Bookings.csv"
hotel_booking_df=pd.read_csv(database)

"""### Dataset First View"""

# Dataset First Look
hotel_booking_df

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(hotel_booking_df.index)

print(hotel_booking_df.columns)

"""### Dataset Information"""

# Dataset Info
hotel_booking_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
hotel_booking_df.drop_duplicates(inplace=True)
uni_num_of_rows=hotel_booking_df.shape[0]
uni_num_of_rows

hotel_booking_df.reset_index()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
null_value=hotel_booking_df.isnull()==True
hotel_booking_df.fillna(np.nan, inplace=True)
hotel_booking_df

# Visualizing the missing values
miss_values=hotel_booking_df.isnull().sum().sort_values(ascending=False)
miss_values

"""### What did you know about your dataset?

Answer - A single file in this data collection analyses different booking details between two hotels: a city hotel and a resort hotel. Includes details like the date the reservation was made, the number of people staying, the number of adults, kids, and/or babies, and the number of parking spaces available, among other things. There are 32 columns and 119390 rows in the entire dataset. Dataset contains duplicate items, such as 31944, which is later removed. Every column in this dataset has a data type, such as an integer, a float, or a text. We note that some of these data types are inaccurate and eliminate those columns afterward. We calculate the distinct value for each column, which represents the actual values for each column.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df_columns=hotel_booking_df.columns
df_columns

# Dataset Describe
hotel_booking_df.describe()

"""Variables Description

1. hotel: Narne of the hotel (Resort Hotel or City Hotel)

2. is canceled: if the booking was canceled (1) or not (0)

3. lead time: Number of days before the actual antral of the Quests

4. antes data year: Year of anival date

5. antval dute month: Month of month arrival date

6. anival date week number: Wock number of year for atval date



10. adults: Number of adults among guests

11. childrens: Number of children among guests

12. babies: Number of babies among pansts

13. mat: Type of meat bocited

14. country: Country of guests

15. mart Designation of market wpmart

14. detribution, chamel: Name of booting distribution chanel

  

18. previous cancellations: Number of previous bookings that were cancelled by the customer prior to the current booking

19. previous bookings_not_canceled: Number of previous bookings not cancelled by the customer prior to the current booking

20. reserved room_type: Code of room type reserved

21. assigned_room_type: Code of room type assigned

22. booking changes: Number of changes/amendments made to the booking

23. deposit type: Type of the deposit made by the guest

24. agent: ID of travel agent who made the booking

25. company: ID of the company that made the booking



27. customer type: Type of customer, assuming one of four categories

28. adr: Average Daily Rate, as defined by dividing the sum of all lodging transactions by the total number of staying nights

29. required.car_parking spaces: Number of car parking spaces required by the customer

30. total of speciel_requests: Number of special requests

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
print(hotel_booking_df.apply(lambda col : col.unique()))

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# lets check , what is the percentage of null values in each column, starting from company.
percentage_company_null= miss_values[0]/uni_num_of_rows*100
percentage_company_null

# to fill the nan values in the  column, lets check which column has null values, we have already started the same
miss_values[:5]

# it is better to drop the column 'company' altogather since the number of missing values is extremly high as compared to number of rows
hotel_booking_df.drop(['company'] ,axis=1 , inplace=True)

# now lets check for agent
percentage_agent_null= miss_values[1]/uni_num_of_rows*100
percentage_agent_null

# As we know there are minimal null values in agent, lets fill this by taking mode of all values
hotel_booking_df['agent'].fillna(value=0, inplace=True)
# we will re-check that column has no null values
hotel_booking_df['agent'].isnull().sum()

# now lets check for null values in country col
percentage_country_null= miss_values[2]/uni_num_of_rows*100
percentage_country_null

# we have less null values in country col, so we will replace null from 'other' as country name
hotel_booking_df['country'].fillna(value='other', inplace=True)
# we will re-check that column has no null values
hotel_booking_df['country'].isnull().sum()

# now lets check for null values in children col
percentage_children_null= miss_values[3]/uni_num_of_rows*100
percentage_children_null

# now lets check whether the database has anyother null values
hotel_booking_df.isnull().sum() # as we can see there is no null values

# change in datatype for required column
# showing the info of the data to check datatype
hotel_booking_df.info()

# total stay in nights
hotel_booking_df['total_stay_in_nights']=hotel_booking_df['stays_in_week_nights'] + hotel_booking_df['stays_in_weekend_nights']
hotel_booking_df['total_stay_in_nights'] # we have created a col for total stays in night by adding week night and weekend night stay col

# we have created a col for revenue by total stay * adr
hotel_booking_df['revenue']=hotel_booking_df['total_stay_in_nights']*hotel_booking_df['adr']
hotel_booking_df['revenue']

# also for information we will also add a col with total guest comming from each booking
hotel_booking_df['total_guest']=hotel_booking_df['adults']+hotel_booking_df['children']+hotel_booking_df['babies']
hotel_booking_df['total_guest'].sum()

# for understanding from col 'is cancelled' we will replace values(0,1) to is cancelled , not cancelled
hotel_booking_df['is_canceled']=hotel_booking_df['is_canceled'].replace([0,1] , ['not canceled', 'is canceled'])
hotel_booking_df['is_canceled']

# same for is_repeated_guest col
hotel_booking_df['is_repeated_guest']=hotel_booking_df['is_repeated_guest'].replace([0,1] , ['not repeated', 'repeated'])
hotel_booking_df['is_repeated_guest']

# now we will check overall revenue hotel wise
hotel_wise_total_revenue=hotel_booking_df.groupby('hotel')['revenue'].sum()
hotel_wise_total_revenue

hotel_booking_df[['hotel','revenue']]





"""### What all manipulations have you done and insights you found?

Answer - We only made a few changes to the date.

Columns added-

We have seen that a few columns are needed in the data for analytical purposes, and these columns can be evaluated.

a) Number of Guests: We may access the overall number of guests and Income by using these columns. This value is obtained by summing the Total number of adults, children, and infants.

b) Income: ADR and total guests are multiplied to find revenue. This column will be used to examine each hotel's growth and profitability.

-Columns deleted-

a)company: As we can see, this column almost has no data. As a result, we had to elliminate this column because it had no bearing on th analysis

Replace values in columns by

is cancelled, fent cancelled, and is a repeat visitor. As we've seen, these columns only hold the value of 0,1 to Indicate that the boycott is now being cancelled. These values (0.1) from "Cancelled" & "not cancelled are changed. The same procedure is used to change 0.1 from "Repeated" and "not repeated in the column To repeated guest". These values will now facilitate greater comprehension during visualisation

-Changes to the values' data lypas in columens-

a) Agent & Kids: We verified that these columns contain float values, which don't make sense in the data because they represent the guest count and agent ID. Therefore, we have updated the 'float' data type of these columns to Integer.

a) Data wrangling must be done before any data from the data set can be visualised.

Data wrangling must be done before any data from the data set can be visualised. We have examined each columns null value in order to determine that. After checking, drop the column using the 'drop method if we find one that has a greater percentage of null values. We are so removed from the "company" column. When there are only a few null values, we fill those null values with the necessary values using the filma) function.

b) In the sarme, we looked to see whether there was any data duplication and discovered that a few rows had duplicate data. As a result, we used the drop duplicates) method to delete those rows from the data set.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

#Let's create a function which will give us bar chart of data respective with a col.

def get_count_from_column_bar(df, column_label):
  df_grpd = df[column_label].value_counts()
  df_grpd = pd.DataFrame({'index' :df_grpd.index, 'count':df_grpd.values})
  return df_grpd

def plot_bar_chart_from_column(df, column_label, t1):
  df_grpd=get_count_from_column_bar(df, column_label)
  fig, ax= plt.subplots(figsize=(14, 6))
  c=['g','r','b','c','y']
  ax.bar(df_grpd['index'], df_grpd['count'], width = 0.4, align ='edge', edgecolor = 'black', linewidth = 4, color=c, linestyle=":", alpha=0.5)
  plt.title(t1, bbox={'facecolor':'0.8', "pad":3})
  plt.legend()
  plt.ylabel('count')
  plt.xticks(rotation =15)
  plt.show()

# Chart - 1 visualization code
def get_count_from_column(df, column_label):

  df_grpd=df[column_label].value_counts()
  df_grpd=pd.DataFrame({'index':df_grpd.index, 'count':df_grpd.values})
  return df_grpd

# plot a pie chart from grouped data

def plot_pie_chart_from_column(df, column_label, t1, exp):

  df_grpd=get_count_from_column(df, column_label)

  fig, ax= plt.subplots(figsize=(14,9))

  ax.pie(df_grpd.loc[:, 'count'], labels= df_grpd.loc[:, 'index'], autopct="%1.2f%%", startangle=98, labeldistance =1.2, explode= exp)
  plt.title(t1, bbox={'facecolor':'0.8', "pad":3})

  ax.axis("equal")

  plt.legend()

  plt.show()

exp1=[0.05,0.05]
plot_pie_chart_from_column(hotel_booking_df,'hotel','Booking percantage of hotel by name',exp1)

"""##### 1. Why did you pick the specific chart?

Answer - To present the data that in which the more booking have been done.

##### 2. What is/are the insight(s) found from the chart?

Answer - Here, we found that the booking number is higher in city hotel which is 61.12% than resort hotel whixh is 38.87%. we can say city hotel has higher consumption.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer - yes, for both hotels the data is making some positive business impact:-
city hotel-provide more services to provide more guest to increase revenue.
resort hotel- find solution to attract guest.

#### Chart - 2
"""

# Chart - 2 visualization code
exp4=[0,0.1]
plot_pie_chart_from_column(hotel_booking_df,'is_canceled','cancellation volume of hotel',exp4)

"""##### 1. Why did you pick the specific chart?

Answer - In this chart we represented the cancellation rate of hotel booking.

##### 2. What is/are the insight(s) found from the chart?

Answer -Here, we found that overall 25% of hotel booking cancelled.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer- we need to check the  reason of cancellation and resolve the issue.

#### Chart - 3
"""

# Chart - 3 visualization code
plot_bar_chart_from_column(hotel_booking_df,'distribution_channel','distribution channel volume')

"""##### 1. Why did you pick the specific chart?

Answer - The followong chart represent that the maximum volume of booking is done from which channel.To represent the number in descending order I used bar chart

##### 2. What is/are the insight(s) found from the chart?

Answer -As we can see TA/TO is highest. recommending to continue booking through TA/TO.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer - Yes this shown positive business impact.

#### Chart - 4
"""

# Chart - 4 visualization code
exp2=[0.2,0,0,0,0,0,0,0,0,0,0,0]
plot_pie_chart_from_column(hotel_booking_df,'arrival_date_month','Month-wise booking',exp2)

"""##### 1. Why did you pick the specific chart?

Answer - To show the percentage share of booking in each month , on overall level.

##### 2. What is/are the insight(s) found from the chart?

Answer - The above percentage shows month may,june and aug have highest number of booking due to holiday season.recommending advertisment to attract more and more customers.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer - Yes, the increased volume of visitors will help hotel to manage revenue in downitme, will also help employee satisfaction and retention.

#### Chart - 5
"""

# Chart - 5 visualization code
exp3=[0,0.2]
plot_pie_chart_from_column(hotel_booking_df,'is_repeated_guest','guest repeating status',exp3)

"""##### 1. Why did you pick the specific chart?

Answer - To show percentage of repeated and non repeated guests.

##### 2. What is/are the insight(s) found from the chart?

Answer -Here, we can see that the number of repeated guest is very less than overall guests.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer -we can give offers to non repeated customers to increase revenue.

#### Chart - 6
"""

# Chart - 6 visualization code
plot_bar_chart_from_column(hotel_booking_df,'assigned_room_type','Assigned room by type')

"""##### 1. Why did you pick the specific chart?

Answer - To show distribution by volume.which room is alloted.

##### 2. What is/are the insight(s) found from the chart?

Answer -This chart shows room type 'A' is most preferred by guests.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer -Yes, positive impact beacuse 'A', 'D', 'E' is most preferred bu guests due to better service offered in room type.

#### Chart - 7
"""

# Chart - 7 visualization code
market_segment_df=pd.DataFrame(hotel_booking_df['market_segment'])

market_segment_df_data = market_segment_df.groupby('market_segment')['market_segment'].count()
market_segment_df_data.sort_values(ascending = False, inplace = True)

plt.figure(figsize=(15,6))
y = np.array([4,5,6])

market_segment_df_data.plot(kind= 'bar', color=['r', 'g', 'y', 'b', 'pink', 'black', 'brown'], fontsize =20, legend='True')

"""##### 1. Why did you pick the specific chart?

Answer -
In this chart, we have seen market segment by which hotel has booked.

##### 2. What is/are the insight(s) found from the chart?

Answer - Online TA has been used most frequently to book hotel by the guest.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Yes, it is creating positive business impact that guests are using Online TA market segment as most prefered to book hotels.

#### Chart - 8
"""

# Chart - 8 visualization code
guest_country_wise= pd.DataFrame(hotel_booking_df[['country','total_guest']])

guest_country_wise_df =guest_country_wise.groupby(['country'])['total_guest'].sum()
guest_country_wise_df.sort_values(ascending =False, inplace = True)

top_10_country_by_guest= guest_country_wise_df.head(10)

plt.figure(figsize=(12,6))

sns.barplot(x=top_10_country_by_guest. index, y=top_10_country_by_guest).set(title='Top 10 Countries by Guest')

print("\n\nPRT- Portugal\nGBR Great Britain & Northern Ireland\nFRA France ESP Spain\nDEU Germany\nITA Italy\nIRL Ireland\nBRA Brazil\nBEL Belgium\nNLD Netherland")

"""##### 1. Why did you pick the specific chart?

Answer -A chart of the top 10 nations is displayed.

##### 2. What is/are the insight(s) found from the chart?

Answer -2. As we can see, the majority of the visitors are from Portugal.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer - To Increase the number of customers, we can increase our marketing efforts and provide enticing deals to visitors from Portugal

#### Chart - 9
"""

# Chart - 9 visualization code
average_adr= hotel_booking_df.groupby('hotel')['adr'].mean()

average_adr

plt.subplots(figsize=(8, 5))

average_adr.plot(kind ='barh', color = ('g', 'r'))

plt.xlabel("Average ADA", fontdict={'fontsize': 12, 'fontweight': 5, 'color': "brown"})

plt.ylabel("Hotel Name", fontdict={'fontsize': 12, 'fontweight': 5, 'color' :'Brown'})
plt.title("Average ADR of Hotel", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Green'})

"""##### 1. Why did you pick the specific chart?

\Answer - I choose bar chart to visualize and compare Average ADA of both the hotels.

##### 2. What is/are the insight(s) found from the chart?

Answer - city hotel has more average ADA as compared to resort hotel

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer - profits earned by city hotel is more than the resort hotel

#### Chart - 10
"""

# Chart - 10 visualization code
plt.figure(figsize = (8,5))

hotel_wise_revenue = hotel_booking_df.groupby('hotel')['revenue'].sum()

hotel_wise_revenue

ax= hotel_wise_revenue.plot(kind= 'bar', color = ('black', 'green'))

plt.xlabel("Hotel", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})

plt.ylabel("Total Revenue", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Brown'})

plt.title("Total Revenue", fontdict={'fontsize': 12, 'fontweight': 5, 'color': 'Green'})

"""##### 1. Why did you pick the specific chart?

Answer - To compare the Total revenue of both the hotels.

##### 2. What is/are the insight(s) found from the chart?

Answer- Total revenue of city hotel is higher than resort hotel.

#### Chart - 12
"""

# Chart - 12 visualization

plt.figure(figsize= (12,10), dpi = 100)
hotel_wise_meal = hotel_booking_df.groupby(['hotel', 'meal'])['meal'].count().unstack()
hotel_wise_meal.plot(kind='bar', figsize = (12,8))
hotel_wise_meal

"""##### 1. Why did you pick the specific chart?

Answer -To display the visitor's preferred dining experience hotel-wise


> Indented block

##### 2. What is/are the insight(s) found from the chart?

Answer - As you can see, guests at both hotels prefer the BB (Bed & Breakfast) meal. In order to increase customer retention and draw in new customers, the hotel can serve more delicious meals during this dinner.

Answer Here

#### Chart - 13
"""

# Chart - 13 visualization code
plt.figure(figsize = (12,6))
sns.scatterplot(y= 'total_stay_in_nights', x='adr', data= hotel_booking_df[hotel_booking_df['adr'] < 1000])
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer -To show comparision and affects of total stay in night vs ADR.

##### 2. What is/are the insight(s) found from the chart?

Answer - Here we see that if guest's stay is decreased ,ADR is High.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

corr_df= hotel_booking_df[['lead_time','previous_cancellations', 'previous_bookings_not_canceled', 'total_guest',

'booking_changes', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']].corr()

f, ax= plt.subplots(figsize=(12, 12))

sns.heatmap(corr_df, annot =True, fmt='.2f', annot_kws={'size': 18}, vmax=1, square=True, cmap="YlGnBu")

"""##### 1. Why did you pick the specific chart?

Answer -To comprehend the relationships among various numerical quantities

##### 2. What is/are the insight(s) found from the chart?

Answer -The axis's highest corelation value is 39% positive and its lowest correlation value is -9% negative.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer -1. For hotel business to flourish few things which we need to consider is high revenue generation, customers satisfaction and employeee retention.
We are able achieve the same by showing the client which are the months which are high in revenue generation by pie chart distribution
Increasing the revenue achieved by bar chart distribution of which typre room are most reserved and what are the months likely for visitors.So for these the client can be well prepare in advance so that minimum grievances would be faced by clients in long run . Qutliers like higher the visitor then adr has reduced drastically was shown in scattered plot so in off season client can eage for bulk booking this will aslo help extra revenue generation.

# **Conclusion**

The guests showed a preference for City hotels, making it the busiest type of hotel
27.5% of all bookings were cancelled.
Only 3.9% of guests revisited the hotels, indicating a low retention rate.
Over 82% of bookings had 0 changes måde, while around 10% had single changes made
The majority of customers (91.6%) did not require car parking spaces.
About 79 1% of bookings were made through travel agents/tour operators
Bed & Breakfast (BB) was the most preferred meal type among guests.
More than 25,000 guests were from Portugal, making it the country with the highest number of guests
Most bookings for City and Resort hotels were made in 2016
City hotels generated more revenue than Resort hotels, with higher average ADR
City hotels had a higner booking cancellation rate of almost 30%
Resort hotels had a higher average lead time
Waiting time was higher for City hotels compared to Resort hotels, indicating City hotels were busier
Resort hotels had the highest number of repeated quests
The optimal stay for both types of hotels was less than 7 days, with people typically staying for a week
About 19% of people did not cancel their bookings despite not getting the reserved room, while only 2.5. cancelled their booking

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""